task2
python-upskill/levelup pull request #7
Opened 2020-04-27 15:49 UTC by ZbigniewBockowski

2020-04-27 16:16 UTC, radowit commented
@ZbigniewBockowski 
Got Internal server error on payload:
```json
{
  "combatants": ["chimera", "banderhobb"],
  "max_rounds": 7	
}
```

2020-04-27 18:09 UTC, ZbigniewBockowski commented
Solved. It is tricky to play with payload with unknown schema ;)

2020-04-27 18:36 UTC, radowit commented
```traceback
Traceback (most recent call last):
  File "/home/dreamwalker/.virtualenvs/system/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 134, in handle
    self.handle_request(listener, req, client, addr)
  File "/home/dreamwalker/.virtualenvs/system/lib/python3.8/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/dreamwalker/.virtualenvs/system/lib/python3.8/site-packages/falcon/api.py", line 269, in __call__
    responder(req, resp, **params)
  File "/home/dreamwalker/Repozytoria/levelup/src/fight_club_api.py", line 15, in on_post
    fighters = self.__load_fighters(fighters_names)
  File "/home/dreamwalker/Repozytoria/levelup/src/fight_club_api.py", line 27, in __load_fighters
    fighter = FightersLoader.load_fighter(name)
  File "/home/dreamwalker/Repozytoria/levelup/src/fighters_loader.py", line 13, in load_fighter
    fighter = FightersLoader.extract_fighter_details(json_data)
  File "/home/dreamwalker/Repozytoria/levelup/src/fighters_loader.py", line 23, in extract_fighter_details
    damage_dice = action["damage"][0]["damage_dice"]
KeyError: 'damage_dice'
```

2020-04-27 21:05 UTC, ZbigniewBockowski commented
And handled cases related to monsters with missing damage_dice information

2020-04-28 07:57 UTC, fancysnake requested changes

2020-04-28 07:57 UTC, fancysnake commented on src/fight_club.py
> +class Fighter:
For the classes here that only store data you could use the [dataclass](https://realpython.com/python-data-classes/) feature.

2020-04-28 07:57 UTC, fancysnake commented on src/fight_club.py
> +WORKS = True
You don't need to add it to all files.

2020-04-28 07:57 UTC, fancysnake commented on src/fight_club.py
> +		winner = fighters[0] if fighters[0].hp > fighters[1].hp else fighters[1]
It would be overkill here, but it's good to know that for longer lists you can use this function:
```python
fighters = sorted(fighters, key=lambda fighter: fighter.hp)
winner = fighters[-1]
loser = fighters[0]
```

2020-04-28 07:57 UTC, fancysnake commented on src/fight_club.py
> +		round_number = 1
First attack should still be determined randomly

2020-04-28 07:57 UTC, fancysnake commented on src/fight_club.py
> +		while fighters[0].hp > 0 and fighters[1].hp > 0 and round_number <= max_rounds_number:
Again, this fix does make sense for bigger lists, but still it's good to know it:
```any([f for fighters if f.hp <=0])```

2020-04-28 07:57 UTC, fancysnake commented on src/fight_club_api.py
> +WORKS = True
Not needed here.

2020-04-28 07:57 UTC, fancysnake commented on src/fighters_loader.py
> +		damage_dice = json_data["actions"][0]["damage"][0]["damage_dice"]
Some monster actions don't deal damage.
Please find the first action that contains damage information.

2020-04-28 07:57 UTC, radowit commented on src/fighters_loader.py
> +		for action in json_data["actions"]:
https://pypi.org/project/jsonpath-ng/

2020-04-28 07:57 UTC, radowit commented on src/fighters_loader.py
> +	@staticmethod
`classmethod`

2020-04-28 08:56 UTC, ZbigniewBockowski commented on src/fight_club.py
> +		while fighters[0].hp > 0 and fighters[1].hp > 0 and round_number <= max_rounds_number:
it has a little bit different format and has to use all for my goal
all(f.hp > 0 for f in fighters)

2020-04-28 09:08 UTC, ZbigniewBockowski commented
Pushed all corrections

2020-04-28 10:00 UTC, merged